### ISSUE TITLE
Arduino precision

### ISSUE THREAD

**Issue by amansaleem** [SaleemLab/MatrixRigs#19]
I had a look at the new Arduino code. One thing I was thinking about is the precision with which things are being read. With the rotary encoder, I know we have the max of 16-bit, 65535, which we do read. And we have to manage the wrap around... right. 
 
I saw that last event times are all 'long', which is 32-bit max 4,294,967,295. Is this going to be a problem when using millis()? Do we need to account for a wrap around? 
 
On the Bonsai end we are using 'utf-8', which might be because we use serial.

**Comment by eabhorrocks** [comment]
current arduino code: ArduinoCode/arduinoCode_edd_dev_april24
current bonsai serial read/parsing: BonsaiWorkflows/BasicArduinoParse_April24Edd.bonsai (This is 2.7.3. Updating to 2.8.2 caused some weird bugs so we are not updating for now)

Looks like Arduino Serial.Print uses ASCII encoding
https://www.arduino.cc/reference/en/language/functions/communication/serial/print/
So perhaps we should be using the us-ascii encoding in Bonsai 'parse' node.

I tried updating the parse node to assume the arduino timestamps are unsigned longs using the format specifier %Li, which is what they are specified as in arduino, however the bonsai parse node doesn't recognise them as %Li, only as ints (%i) as far as I can tell. I also tried some other possible specifiers but they either weren't valid or didn't successfully parse.

In terms of whether this matters?
The wheel as an int in bonsai successfully reaches the max value.
Not sure if we have an issue with the arduino timestamps being encoded as ints in bonsai, but it would be nice to keep them as unsigned longs in bonsai if possible
